image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - /^release-.*$/

doc:
  stage: deploy
  script:
    - uwsgi --socket :8000 --master --processes=4 --wsgi-file /usr/local/ASKCOS/askcos/wsgi.py
    - pip install sphinx
    - cd docs/
    - python -m sphinx.ext.apidoc -f -o ./ ..
    - python -m sphinx -b html -d _build/doctrees   . _build/html
  artifacts:
    paths:
    - docs/_build/html/
  only:
    - documentation
